/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.example.CreditCardValidator.validateCreditCard;

public class App {
    public static void main(String[] args) {

    }
}
